### ISSUE TITLE
ゲームプレイ中のプレイヤーの音量の計測

### ISSUE THREAD

**Issue by yanoty3d** [smalab/JumpGame#6]
プレイ中に、連続的に音量データをとる
- [x] CSV形式で、連続音量データを保存する
- [ ] 普通に話すときの音量を記録する

**Comment by oitsmalab** [comment]
csv形式で音量データを保存できるようにはなりました。
普通に話すときの音量はcsv形式で取得したデータの平均値を取ろうかと思っています。
